name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - pip:
    - jupyterlite-core==0.1.0
    - jupyterlite-xeus-python==0.7.0
    - jlab-enhanced-cell-toolbar==3.5.1
    - ./amperitycolors
    - ./amperityfrontend
    - nbformat==5.8.0
    - ipycanvas==0.13.1
    - ipywidgets==8.0.6
    - ipyevents==2.0.1
    - ipympl==0.9.3
    - plotly==5.14.1
    - ipydatagrid==1.1.14
    - ipycytoscape==1.3.3
    - seaborn==0.12.2
    - altair==4.2.2
    - ipyvuetify==1.8.4