name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - nbformat==5.8.0
  - ipycanvas==0.13.1
  - ipywidgets==8.0.6
  - ipyevents==2.0.1
  - ipympl==0.9.3
  - plotly==5.14.1
  - ipydatagrid==1.1.14
  - ipycytoscape==1.3.3
  - seaborn==0.12.2
  - altair==4.2.2
  - ipyvuetify==1.8.4